import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import TopUp from "@/components/TopUp/TopUp";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fontSans.variable}>
        <TopUp />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
